auth_mode = "ON"

[credentials.usernames.murphey]
name = "Murphey Coy"
email = "rmcoy2y@gmail.com"
password = "$2b$12$9eoQypxuzyrOwwErAel4VOl5HgoEgCUj5u8YIhIelKnlWkyJ6iWau"  # bet247
role = "admin"

[credentials.usernames.tester]
name = "Guest"
email = ""
password = "$2b$12$uNiAG1j3QkaBnT2LzeSjYOy7fWxT47.OyJEW5/Z./JE8h5V0h0gPS"  # _guest
role = "guest"

[credentials.usernames.beta]
name = "Beta Tester"
email = ""
# password: beta_demo
password = "$2b$12$3Jx4s6o8mX7L8a0y3Xxcje1q1tP5C9YHnB9f6oGdL1a6mH1cRjM4K"
role = "beta"
